In [112]:
import torch
from torch import nn
from torch.utils.data import Dataset, DataLoader, SubsetRandomSampler
import pandas as pd
import numpy as np
import random
import collections
import csv
from sklearn.model_selection import train_test_split, KFold

In [45]:
def create_ancestors_dict(path_to_ancestors, path_to_weights=None):
    """_summary_

    Args:
        path_to_ancestors (string): path to the ancestors file
        path_to_weights (string, optional): path to the weight file. Defaults to None, uniform.

    Returns:
        dict: ancestors dict d[MESH][ancestors] for the ancestors list and d[MESH][proba] for the associated probabilities
    """

    ancestors_dict = collections.defaultdict(dict)

    # From ancestors csv file to dict
    ancestors = pd.read_csv(path_to_ancestors)
    pre_ancestors_dict = ancestors.groupby('MESH')['MESH_ANCESTOR'].apply(list).to_dict()

    # Create weight dict
    weights = dict()
    if path_to_weights:
        weights = pd.read_csv(path_to_weights).groupby("MESH")["TOTAL_PMID_MESH"].apply(int).to_dict()

    # browse ancestors and insert weights
    for mesh, ancestors in pre_ancestors_dict.items():

        # Add the MeSH itselft to the list of ancestors
        ancestors_dict[mesh]["ancestors"] = ancestors
        inverse_weights = [1/(weights.get(ancestor, 0) + 1) for ancestor in ancestors]
        ancestors_dict[mesh]["proba"] = [w/sum(inverse_weights) for w in inverse_weights]

    return ancestors_dict

In [110]:
ancestors_dict = create_ancestors_dict("data/mesh_ancestors.csv", "data/mesh_pmids_count.csv")
print(ancestors_dict["D010084"])

{'ancestors': ['D010084', 'D004734', 'D008660', 'D055598'], 'proba': [0.25, 0.25, 0.25, 0.25]}


In [89]:
def create_samples(n, data, w, ancestors):
    """
    n(int): nombre d'exemples à générer
    data(fichier format CSV): les pmids avec les mesh annotés
    w(int): taille de la fenêtre, nombre de meshs pour le contexte
    ancestors(dico {mesh:poids}): ancêtres du mesh dans arbre
    """
    
    context = []
    target = []
    
    df = pd.read_csv(data)
    pmids = [id for id in df["PMID"].unique()]
    if n > len(pmids):
        print("Warning : n > number of pmids in data")
        n = len(pmids)

    i = 0
    while i < n:
        pmid = random.choice(pmids)
        if len(pmids) == 0:
            i = n
        mesh = df[df["PMID"] == pmid]["MESH"].to_list()

        # target = 1 mesh au hasard
        mesh_target = mesh.pop(random.randrange(len(mesh)))
        mesh_target = random.choices(ancestors[mesh_target]["ancestors"], weights=ancestors[mesh_target]["proba"], k=1)
        target.append(mesh_target)

        # contexte = w mesh au hasard
        if w > len(mesh):
            # supprimer
            target.pop()
        else:
            mesh_context = [mesh.pop(random.randrange(len(mesh))) for j in range(w)]
            mesh_context = [random.choices(ancestors[m]["ancestors"], weights=ancestors[m]["proba"], k=1)[0] for m in mesh_context]
            context.append(mesh_context)
            i += 1
            
    with open("data/context.csv", "w") as f:
        write = csv.writer(f)
        write.writerows(context)
    with open("data/target.csv", "w") as f:
        write = csv.writer(f)
        write.writerows(target)

In [111]:
create_samples(1000, "data/sample_pmid_mesh.csv", 6, ancestors_dict)

In [49]:
class MyDataset(Dataset):
    def __init__(self, context, target, vocab):
        """
        context(liste de liste): mesh du contexte
        target(liste): mesh cible
        vocab(dico {mesh:indice_du_1}) : indice du 1 pour le one shot vector qui représente le mesh
        """
        self.context = context
        self.target = target
        self.vocab = vocab
        
    def __len__(self):
        # taille vocab
        return len(self.target)
        
    def __getitem__(self, idx):
        if idx >= self.__len__():
            print("Error : index out of bounds")
            return None
            
        vector_target = np.zeros(len(self.vocab))
        vector_target[self.vocab[self.target[idx][0]]] = 1
        
        vector_context = np.zeros(len(self.vocab))
        for mesh in self.context[idx]:
            vector_context[self.vocab[mesh]] += 1
            
        return vector_context, vector_target
        

In [116]:
class MeSH2VecDataset(Dataset):
    """
    Create a Dataset for MeSH2VecDataset

    Args:
        f_input (str): path to the input file. A comma separated csv file where each line correspond to a context
        f_target (str): path to the target file. A csv file where each line correspond to target MeSH. Must be the same number of lines as in the context file.
        f_vocab (str): path to the vocabulary file. A csv file, one line by MeSH. The line number will five the id of the MeSH in the vocab.
        f_labels (str): path to the labels file. A two columns csv file, with MeSH identifier in the first column and the corresponding label in the second 

    Return: a list of two tensors: (tensor of length w corresponding to the context input ids, tensor of length 1 corresponding to the id of the target MeSH)
    """


    def __init__(self, f_input, f_target, f_vocab, f_labels):
        self.input = self.read(f_input).tolist()
        self.target = self.read(f_target).squeeze().tolist()
        self.vocab = self.read_vocab(f_vocab)
        self.vocab_size = len(self.vocab)
        self.inverse_vocab = {v: k for k, v in self.vocab.items()}
        self.labels = self.mesh2label_dict(f_labels)
        self.n = len(self.input)
        self.w = len(self.input[0])

    def __len__(self):
        return self.n

    def __getitem__(self, index):
        x = torch.tensor([self.vocab[m] for m in self.input[index]], dtype=torch.int32)
        y = torch.tensor(self.vocab[self.target[index]], dtype=torch.int32)
        return x, y

    def read(self, path):
        f = pd.read_csv(path, header=None, dtype=str)
        return f.values

    def read_vocab(self, f_vocab):
        v = self.read(f_vocab).squeeze().tolist()

        # Check that all input are in vocab:
        flat_input = list(np.concatenate(self.input).flat)
        if not all([j in v for j in flat_input]):
            print("[WARNING] Some MeSH in input are not in the vocabulary")
        
        if not all([j in v for j in self.target]):
            print("[WARNING] Some MeSH in target are not in the vocabulary")
        
        return dict(zip(v, range(len(v))))

    def mesh2label_dict(self, f_labels):
        labels = self.read(f_labels)
        return dict(zip(labels[:,0].tolist(), labels[:,1].tolist()))
    
    def tensor2labels(self, t):
        return [self.labels.get(self.inverse_vocab.get(int(i), "NaN"), "No label Found") for i in t]



In [128]:
dataset = MeSH2VecDataset("data/context.csv", "data/target.csv", "data/mesh_vocab.csv", "data/mesh_labels.csv")

In [129]:
dataset = MeSH2VecDataset(f_input="data/context.csv", f_target="data/target.csv", f_vocab="data/mesh_vocab.csv", f_labels="data/mesh_labels.csv")
dataloader = DataLoader(dataset, 100)

In [92]:
dataset[0]

(tensor([2030, 2100, 3386, 9868, 8831, 6433], dtype=torch.int32),
 tensor(6436, dtype=torch.int32))

In [93]:
for i, j in enumerate(dataloader):
    print(i)
    print(j[0].shape)
    print(j[1].shape)

0
torch.Size([100, 6])
torch.Size([100])
1
torch.Size([100, 6])
torch.Size([100])
2
torch.Size([100, 6])
torch.Size([100])
3
torch.Size([100, 6])
torch.Size([100])
4
torch.Size([100, 6])
torch.Size([100])
5
torch.Size([100, 6])
torch.Size([100])
6
torch.Size([100, 6])
torch.Size([100])
7
torch.Size([100, 6])
torch.Size([100])
8
torch.Size([100, 6])
torch.Size([100])
9
torch.Size([100, 6])
torch.Size([100])


In [114]:
train, test = train_test_split(dataset, train_size=0.9, test_size=0.1, random_state=42)
print("Train : "+str(len(train)))
print("Test : "+str(len(test)))

kfold = KFold(5, shuffle=True, random_state=42)
for n, (train_i, test_i) in enumerate(kfold.split(train)):
    print("Folder "+str(n))
    print("\tLen train : "+str(len(train_i)))
    print("\tLen test : "+str(len(test_i)))
    
    train_sampler = SubsetRandomSampler(train_i)
    train_loader = DataLoader(train, 100, sampler=train_sampler)
    for i, j in enumerate(train_loader):
        print("\tTrain DataLoader "+str(i))
        print("\t\t["+str(j[0].shape)+"  "+str(j[1].shape)+"]")
        
    test_sampler = SubsetRandomSampler(test_i)
    test_loader = DataLoader(train, 100, sampler=test_sampler)
    for i, j in enumerate(test_loader):
        print("\tTest DataLoader "+str(i))
        print("\t\t["+str(j[0].shape)+"  "+str(j[1].shape)+"]")

Train : 900
Test : 100
Folder 0
	Len train : 720
	Len test : 180
	Train DataLoader 0
		[torch.Size([100, 6])  torch.Size([100])]
	Train DataLoader 1
		[torch.Size([100, 6])  torch.Size([100])]
	Train DataLoader 2
		[torch.Size([100, 6])  torch.Size([100])]
	Train DataLoader 3
		[torch.Size([100, 6])  torch.Size([100])]
	Train DataLoader 4
		[torch.Size([100, 6])  torch.Size([100])]
	Train DataLoader 5
		[torch.Size([100, 6])  torch.Size([100])]
	Train DataLoader 6
		[torch.Size([100, 6])  torch.Size([100])]
	Train DataLoader 7
		[torch.Size([20, 6])  torch.Size([20])]
	Test DataLoader 0
		[torch.Size([100, 6])  torch.Size([100])]
	Test DataLoader 1
		[torch.Size([80, 6])  torch.Size([80])]
Folder 1
	Len train : 720
	Len test : 180
	Train DataLoader 0
		[torch.Size([100, 6])  torch.Size([100])]
	Train DataLoader 1
		[torch.Size([100, 6])  torch.Size([100])]
	Train DataLoader 2
		[torch.Size([100, 6])  torch.Size([100])]
	Train DataLoader 3
		[torch.Size([100, 6])  torch.Size([100])]
	Tr

In [172]:
class NeuralNetwork(nn.Module):
    def __init__(self, n, v):
        """
        w(int): taille fenêtre
        n(int): taille embedding
        v(int): taille vocab
        """
        super(NeuralNetwork, self).__init__()
        self.n = n
        self.v = v
        self.hidden1 = nn.Embedding(self.v, self.n, max_norm = True)
        self.hidden2 = nn.Linear(self.n, self.v, bias = False)

    def forward(self, input):
        x = self.hidden1(input)
        x = torch.mean(x, axis = 1)
        x = self.hidden2(x)
        return x
        

In [173]:
vocab_size = dataset.vocab_size
myModule = NeuralNetwork(50, vocab_size)


In [176]:
for p in myModule.parameters():
    print(p)

Parameter containing:
tensor([[-1.1878,  0.7412, -0.5329,  ..., -0.6887, -1.7609, -2.2322],
        [ 1.0483, -0.7755,  0.0122,  ...,  0.5887, -1.0571,  0.1623],
        [ 1.9819, -0.6975,  2.2825,  ...,  0.9734,  0.0047,  2.1734],
        ...,
        [-0.9758,  0.0923, -0.8815,  ...,  0.4994,  1.4007,  1.3084],
        [ 1.3783, -0.1214,  0.2811,  ..., -1.1937, -0.2114,  0.6996],
        [-1.6322, -0.1479, -1.9099,  ...,  0.1920, -1.3706, -0.7814]],
       requires_grad=True)
Parameter containing:
tensor([[ 0.0712,  0.0380, -0.1403,  ..., -0.1286, -0.1104,  0.0313],
        [ 0.1022, -0.0081,  0.0965,  ...,  0.1381,  0.0746,  0.0510],
        [-0.1330,  0.0474, -0.1232,  ..., -0.1279,  0.1160, -0.0017],
        ...,
        [ 0.0112, -0.1113, -0.0643,  ..., -0.0064,  0.0029,  0.0332],
        [-0.0789,  0.1259,  0.0034,  ...,  0.0312, -0.0469,  0.0534],
        [-0.1103, -0.0588,  0.1194,  ...,  0.1006,  0.1278,  0.0237]],
       requires_grad=True)


In [156]:
input, target = next(iter(dataloader))
x = myModule(input)

In [157]:
print(x.shape)

torch.Size([100, 12761])
